"""
residual_live.schemas.settlement_notice
=========================================
SettlementNotice — an auditable, human-approvable payment obligation document.

This is the output artifact of the Schwellenwächter ADK agent.  It represents
a *complete*, *self-contained* record of a royalty obligation: who owes what
to whom, derived from which events, under which contract clauses — with a
tamper-evident audit chain.

Audit verification design
--------------------------
Each SettlementNotice carries:

1. ``audit_log``  — an ordered list of ``AuditEntry`` records, one per
   contributing RoyaltyEvent.  Each entry records the event_id, the matching
   rule clause reference, the computed contribution, and a per-entry SHA-256
   hash.  The hash covers (event_id, rule_id, contribution_amount,
   contribution_currency, entry_index) so any post-hoc mutation is detectable.

2. ``audit_chain_hash`` — a single SHA-256 fingerprint of the *entire*
   ordered list of per-entry hashes.  Recomputing this hash and comparing it
   to the stored value verifies that the audit_log has not been tampered with
   or reordered.

3. ``notice_hash`` — a top-level fingerprint of the final notice payload
   (all monetary totals + audit_chain_hash).  Used by downstream systems
   (e.g. the approval workflow) to detect any mutation after generation.

Workflow states
---------------
DRAFT      → generated by the agent, not yet reviewed
PENDING    → submitted for human approval (Human-in-the-Loop gate)
APPROVED   → approved by authorised user; triggers payment instruction
REJECTED   → rejected; reason stored in ``rejection_reason``
SUPERSEDED → replaced by a corrected notice (links to ``superseded_by``)
PAID       → payment confirmed by treasury system
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, model_validator

from ._types import Money, compute_sha256  # noqa: F401


# ---------------------------------------------------------------------------
# SettlementStatus
# ---------------------------------------------------------------------------

class SettlementStatus(str, Enum):
    """Lifecycle state of the SettlementNotice."""
    DRAFT = "draft"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SUPERSEDED = "superseded"
    PAID = "paid"


# ---------------------------------------------------------------------------
# AuditEntry — one line in the audit log
# ---------------------------------------------------------------------------

class AuditEntry(BaseModel):
    """
    Immutable record of a single RoyaltyEvent's contribution to a notice.

    The ``entry_hash`` is computed from the entry's own fields and its index
    in the audit_log list, making reordering detectable.
    """

    model_config = {"frozen": True}

    entry_index: int = Field(
        ge=0,
        description="Zero-based position of this entry in the audit_log list.",
    )

    event_id: str = Field(
        description="References RoyaltyEvent.event_id.",
    )

    occurred_at: datetime = Field(
        description="Copied from RoyaltyEvent.occurred_at for self-contained audit record.",
    )

    rule_id: str = Field(
        description="References the ContractRule.rule_id that was applied.",
    )

    clause_reference: str = Field(
        description="Human-readable clause text copied from ContractRule.clause_reference.",
        examples=["§ 4.2 (b)"],
    )

    usage_metric_label: str = Field(
        description=(
            "Human-readable description of the usage metric used "
            "(e.g. '95.5 stream_minutes', '3 plays')."
        ),
        examples=["95.5 stream_minutes", "3 plays"],
    )

    contribution: Money = Field(
        description="Monetary contribution of this event to the notice total.",
    )

    computation_note: str = Field(
        description=(
            "Short explanation of how contribution was computed "
            "(e.g. '95.5 min × USD 0.0012/min')."
        ),
        examples=["95.5 min × USD 0.0012/min", "threshold crossed: 100,000 min × USD 0.0012"],
    )

    entry_hash: str = Field(
        description=(
            "SHA-256 of (entry_index, event_id, rule_id, "
            "contribution.amount, contribution.currency). "
            "Computed at creation; any mutation invalidates the hash."
        ),
    )

    @classmethod
    def create(
        cls,
        *,
        entry_index: int,
        event_id: str,
        occurred_at: datetime,
        rule_id: str,
        clause_reference: str,
        usage_metric_label: str,
        contribution: Money,
        computation_note: str,
    ) -> "AuditEntry":
        """
        Factory method — computes entry_hash automatically.

        Always use this instead of the raw constructor to ensure hash integrity.
        """
        payload = {
            "entry_index": entry_index,
            "event_id": event_id,
            "rule_id": rule_id,
            "contribution_amount": str(contribution.amount),
            "contribution_currency": contribution.currency,
        }
        entry_hash = compute_sha256(payload)
        return cls(
            entry_index=entry_index,
            event_id=event_id,
            occurred_at=occurred_at,
            rule_id=rule_id,
            clause_reference=clause_reference,
            usage_metric_label=usage_metric_label,
            contribution=contribution,
            computation_note=computation_note,
            entry_hash=entry_hash,
        )

    def verify(self) -> bool:
        """
        Return True if the stored entry_hash matches a fresh recomputation.

        Call this when loading a notice from persistent storage to detect
        tampering.
        """
        payload = {
            "entry_index": self.entry_index,
            "event_id": self.event_id,
            "rule_id": self.rule_id,
            "contribution_amount": str(self.contribution.amount),
            "contribution_currency": self.contribution.currency,
        }
        return compute_sha256(payload) == self.entry_hash


# ---------------------------------------------------------------------------
# SettlementNotice
# ---------------------------------------------------------------------------

class SettlementNotice(BaseModel):
    """
    A complete, auditable royalty payment obligation document.

    Generated by the Schwellenwächter ADK agent when accumulated usage for a
    contract/period crosses a payment threshold (or at a scheduled settlement
    date).  Submitted to the Human-in-the-Loop approval gate before any
    payment instruction is issued.

    Audit integrity
    ---------------
    Call ``verify_audit_integrity()`` after loading from storage to confirm
    that neither the individual AuditEntry records nor the notice totals have
    been altered.

    Example::

        entry = AuditEntry.create(
            entry_index=0,
            event_id="evt-001",
            occurred_at=datetime(2026, 9, 7, 14, 32, tzinfo=timezone.utc),
            rule_id="RULE-NF-DE-2025-001",
            clause_reference="§ 4.2 (b)",
            usage_metric_label="95500 stream_minutes",
            contribution=Money(amount="114.60", currency="USD"),
            computation_note="95500 min × USD 0.0012/min",
        )
        notice = SettlementNotice.create(
            title_id="TITLE-001",
            title_name="The Last Frontier",
            contract_id="CONTRACT-2025-NF-DE-001",
            licensor_id="LICENSOR-STUDIO-42",
            licensor_name="Frontier Studios GmbH",
            licensee_id="LICENSEE-NF-42",
            licensee_name="StreamCo Europe",
            period_from=datetime(2026, 9, 1, tzinfo=timezone.utc),
            period_until=datetime(2026, 9, 30, tzinfo=timezone.utc),
            currency="USD",
            audit_log=[entry],
        )
    """

    model_config = {
        "populate_by_name": True,
    }

    # --- Identity -----------------------------------------------------------

    notice_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Globally unique notice identifier.",
    )

    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when this notice was generated by the agent.",
    )

    status: SettlementStatus = Field(
        default=SettlementStatus.DRAFT,
        description="Current workflow state of this notice.",
    )

    # --- Parties ------------------------------------------------------------

    title_id: str = Field(description="References RoyaltyEvent.title_id.")
    title_name: str = Field(description="Human-readable title name.")

    contract_id: str = Field(
        description="The licence contract this notice is issued under.",
    )

    licensor_id: str = Field(
        description="Identifier of the rights holder receiving payment.",
        examples=["LICENSOR-STUDIO-42"],
    )

    licensor_name: str = Field(
        description="Display name of the licensor.",
        examples=["Frontier Studios GmbH"],
    )

    licensee_id: str = Field(
        description="Identifier of the party obligated to pay.",
        examples=["LICENSEE-NF-42"],
    )

    licensee_name: str = Field(
        description="Display name of the licensee.",
        examples=["StreamCo Europe"],
    )

    # --- Settlement period --------------------------------------------------

    period_from: datetime = Field(
        description="Inclusive start of the settlement period (timezone-aware).",
    )

    period_until: datetime = Field(
        description=(
            "Exclusive end of the settlement period (timezone-aware). "
            "All contributing events have occurred_at in [period_from, period_until)."
        ),
    )

    # --- Monetary totals ----------------------------------------------------

    currency: str = Field(
        min_length=3,
        max_length=3,
        pattern=r"^[A-Z]{3}$",
        description="ISO-4217 settlement currency for all totals in this notice.",
    )

    gross_royalty_due: Money = Field(
        description="Sum of all AuditEntry contributions before any deductions.",
    )

    withholding_tax: Optional[Money] = Field(
        default=None,
        description=(
            "Withholding tax amount if applicable (same currency as "
            "gross_royalty_due).  Deducted to reach net_royalty_due."
        ),
    )

    net_royalty_due: Money = Field(
        description=(
            "Final amount payable: gross_royalty_due minus withholding_tax. "
            "Validated against the audit_log sum."
        ),
    )

    payment_due_date: Optional[datetime] = Field(
        default=None,
        description=(
            "Contractual payment deadline.  Set by the agent from the "
            "contract terms at notice creation time."
        ),
    )

    # --- Audit trail --------------------------------------------------------

    audit_log: list[AuditEntry] = Field(
        min_length=1,
        description=(
            "Ordered list of per-event audit entries.  One entry per "
            "contributing RoyaltyEvent.  Never mutate after creation."
        ),
    )

    audit_chain_hash: str = Field(
        description=(
            "SHA-256 of the concatenated entry_hash values (in order). "
            "Detects reordering or entry insertion/deletion."
        ),
    )

    notice_hash: str = Field(
        description=(
            "SHA-256 of the top-level notice payload "
            "(notice_id, contract_id, gross_royalty_due, net_royalty_due, "
            "audit_chain_hash).  Guards the final figures against mutation."
        ),
    )

    # --- Approval metadata --------------------------------------------------

    approved_by: Optional[str] = Field(
        default=None,
        description="User ID of the approver (set when status → APPROVED).",
    )

    approved_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp of approval.",
    )

    rejection_reason: Optional[str] = Field(
        default=None,
        description="Reason for rejection (set when status → REJECTED).",
    )

    superseded_by: Optional[str] = Field(
        default=None,
        description=(
            "notice_id of the corrected notice that supersedes this one "
            "(set when status → SUPERSEDED)."
        ),
    )

    # --- Validators ---------------------------------------------------------

    @model_validator(mode="after")
    def validate_period(self) -> "SettlementNotice":
        if self.period_until <= self.period_from:
            raise ValueError("period_until must be strictly after period_from.")
        return self

    @model_validator(mode="after")
    def validate_currency_consistency(self) -> "SettlementNotice":
        """All monetary fields must share the same settlement currency."""
        for field_name, money in (
            ("gross_royalty_due", self.gross_royalty_due),
            ("net_royalty_due", self.net_royalty_due),
            ("withholding_tax", self.withholding_tax),
        ):
            if money is not None and money.currency != self.currency:
                raise ValueError(
                    f"{field_name}.currency={money.currency!r} "
                    f"does not match notice currency={self.currency!r}."
                )
        for i, entry in enumerate(self.audit_log):
            if entry.contribution.currency != self.currency:
                raise ValueError(
                    f"audit_log[{i}].contribution.currency="
                    f"{entry.contribution.currency!r} "
                    f"does not match notice currency={self.currency!r}."
                )
        return self

    @model_validator(mode="after")
    def validate_audit_log_indices(self) -> "SettlementNotice":
        """entry_index must be 0, 1, 2, … without gaps."""
        for expected, entry in enumerate(self.audit_log):
            if entry.entry_index != expected:
                raise ValueError(
                    f"audit_log[{expected}].entry_index={entry.entry_index} "
                    f"(expected {expected}); indices must be contiguous from 0."
                )
        return self

    # --- Factory ------------------------------------------------------------

    @classmethod
    def create(
        cls,
        *,
        title_id: str,
        title_name: str,
        contract_id: str,
        licensor_id: str,
        licensor_name: str,
        licensee_id: str,
        licensee_name: str,
        period_from: datetime,
        period_until: datetime,
        currency: str,
        audit_log: list[AuditEntry],
        withholding_tax: Optional[Money] = None,
        payment_due_date: Optional[datetime] = None,
        notice_id: Optional[str] = None,
    ) -> "SettlementNotice":
        """
        Factory that computes all hashes and derived totals automatically.

        This is the only correct way to create a SettlementNotice — it
        guarantees hash integrity by computing audit_chain_hash and
        notice_hash from the provided data.
        """
        if not audit_log:
            raise ValueError("audit_log must contain at least one entry.")

        # Reindex entries to enforce 0, 1, 2, … ordering
        reindexed: list[AuditEntry] = []
        for i, entry in enumerate(audit_log):
            if entry.entry_index != i:
                # Recreate with corrected index and recomputed hash
                entry = AuditEntry.create(
                    entry_index=i,
                    event_id=entry.event_id,
                    occurred_at=entry.occurred_at,
                    rule_id=entry.rule_id,
                    clause_reference=entry.clause_reference,
                    usage_metric_label=entry.usage_metric_label,
                    contribution=entry.contribution,
                    computation_note=entry.computation_note,
                )
            reindexed.append(entry)

        # Compute gross total
        gross = sum(
            (e.contribution.amount for e in reindexed),
            start=Decimal("0.00"),
        )
        gross_money = Money(amount=gross, currency=currency)

        # Net = gross - withholding
        wht_amount = withholding_tax.amount if withholding_tax else Decimal("0.00")
        net_money = Money(amount=gross - wht_amount, currency=currency)

        # audit_chain_hash: SHA-256 of ordered entry hashes
        chain_payload = {"chain": [e.entry_hash for e in reindexed]}
        audit_chain_hash = compute_sha256(chain_payload)

        # notice_hash: fingerprint of the final figures
        nid = notice_id or str(uuid.uuid4())
        notice_payload = {
            "notice_id": nid,
            "contract_id": contract_id,
            "gross_royalty_due_amount": str(gross_money.amount),
            "gross_royalty_due_currency": gross_money.currency,
            "net_royalty_due_amount": str(net_money.amount),
            "net_royalty_due_currency": net_money.currency,
            "audit_chain_hash": audit_chain_hash,
        }
        notice_hash = compute_sha256(notice_payload)

        return cls(
            notice_id=nid,
            title_id=title_id,
            title_name=title_name,
            contract_id=contract_id,
            licensor_id=licensor_id,
            licensor_name=licensor_name,
            licensee_id=licensee_id,
            licensee_name=licensee_name,
            period_from=period_from,
            period_until=period_until,
            currency=currency,
            gross_royalty_due=gross_money,
            withholding_tax=withholding_tax,
            net_royalty_due=net_money,
            payment_due_date=payment_due_date,
            audit_log=reindexed,
            audit_chain_hash=audit_chain_hash,
            notice_hash=notice_hash,
        )

    # --- Audit verification -------------------------------------------------

    def verify_audit_integrity(self) -> dict[str, bool | list[int]]:
        """
        Verify the tamper-evidence of this notice.

        Returns a dict with keys:
          ``entries_valid``       — True if every AuditEntry.verify() passes
          ``chain_valid``         — True if audit_chain_hash matches a fresh recompute
          ``notice_valid``        — True if notice_hash matches a fresh recompute
          ``failed_entry_indices``— list of entry_index values that failed verify()
          ``all_valid``           — True only if all three checks pass

        Example::

            result = notice.verify_audit_integrity()
            assert result["all_valid"], f"Audit integrity failure: {result}"
        """
        failed: list[int] = [
            e.entry_index for e in self.audit_log if not e.verify()
        ]
        entries_valid = len(failed) == 0

        # Recompute chain hash
        chain_payload = {"chain": [e.entry_hash for e in self.audit_log]}
        chain_valid = compute_sha256(chain_payload) == self.audit_chain_hash

        # Recompute notice hash
        notice_payload = {
            "notice_id": self.notice_id,
            "contract_id": self.contract_id,
            "gross_royalty_due_amount": str(self.gross_royalty_due.amount),
            "gross_royalty_due_currency": self.gross_royalty_due.currency,
            "net_royalty_due_amount": str(self.net_royalty_due.amount),
            "net_royalty_due_currency": self.net_royalty_due.currency,
            "audit_chain_hash": self.audit_chain_hash,
        }
        notice_valid = compute_sha256(notice_payload) == self.notice_hash

        return {
            "entries_valid": entries_valid,
            "chain_valid": chain_valid,
            "notice_valid": notice_valid,
            "failed_entry_indices": failed,
            "all_valid": entries_valid and chain_valid and notice_valid,
        }

    def approve(self, approved_by: str) -> "SettlementNotice":
        """
        Return a new notice in APPROVED state (immutable update pattern).

        Raises ValueError if the notice is not in PENDING state.
        """
        if self.status != SettlementStatus.PENDING:
            raise ValueError(
                f"Can only approve a PENDING notice; current status={self.status.value}."
            )
        return self.model_copy(
            update={
                "status": SettlementStatus.APPROVED,
                "approved_by": approved_by,
                "approved_at": datetime.now(timezone.utc),
            }
        )

    def reject(self, reason: str) -> "SettlementNotice":
        """Return a new notice in REJECTED state."""
        if self.status != SettlementStatus.PENDING:
            raise ValueError(
                f"Can only reject a PENDING notice; current status={self.status.value}."
            )
        return self.model_copy(
            update={
                "status": SettlementStatus.REJECTED,
                "rejection_reason": reason,
            }
        )

    def submit_for_approval(self) -> "SettlementNotice":
        """Transition DRAFT → PENDING."""
        if self.status != SettlementStatus.DRAFT:
            raise ValueError(
                f"Can only submit a DRAFT notice; current status={self.status.value}."
            )
        return self.model_copy(update={"status": SettlementStatus.PENDING})
